var b=Object.defineProperty;var v=Object.getOwnPropertyDescriptor;var j=Object.getOwnPropertyNames;var S=Object.prototype.hasOwnProperty;var C=(r,e)=>()=>(r&&(e=r(r=0)),e);var y=(r,e)=>()=>(e||r((e={exports:{}}).exports,e),e.exports);var f=(r,e,n,u)=>{if(e&&typeof e=="object"||typeof e=="function")for(let s of j(e))!S.call(r,s)&&s!==n&&b(r,s,{get:()=>e[s],enumerable:!(u=v(e,s))||u.enumerable});return r},c=(r,e,n)=>(f(r,e,"default"),n&&f(n,e,"default"));var w=r=>f(b({},"__esModule",{value:!0}),r);import{Buffer as a}from"https://registry.koishi.chat/modules/buffer/index.js";import l from"https://registry.koishi.chat/modules/process/index.js";var o=C(()=>{});var i={};import*as R from"https://registry.koishi.chat/modules/koishi/index.js";var h=C(()=>{o();c(i,R)});var m=y(g=>{"use strict";o();Object.defineProperty(g,"__esModule",{value:!0});g.logger=void 0;var $=(h(),w(i));g.logger=new $.Logger("milk-ikun")});var _=y(d=>{"use strict";o();Object.defineProperty(d,"__esModule",{value:!0});d.countryCheck=void 0;var p=m();async function q(r){try{let{data:e}=await r.http.axios("http://ip-api.com/json/",{validateStatus:n=>!0});if(p.logger.debug(e),e){if(e&&e.status!=="success")return!1}else return!1;return e.countryCode&&e.countryCode!=="CN"?(p.logger.debug(`check countries and regions success: ${e.countryCode} (${e.country}), unsupported!`),!1):(p.logger.debug(`check countries and regions success: ${e.countryCode} (${e.country}), is supported!`),!0)}catch(e){return p.logger.warn(`check countries and regions error: ${e.stack??e}`),!1}}d.countryCheck=q});var O=y(t=>{o();Object.defineProperty(t,"__esModule",{value:!0});t.apply=t.Config=t.usage=t.name=t.using=void 0;var k=(h(),w(i)),x=m(),K=_();t.using=[];t.name="milk-ikun";t.usage=`
# koishi-plugin-milk-ikun
  ## 让您的机器人不再小黑子!

<h3 style="margin: 0; margin-bottom: 8px;">最新版本:
    <a target="_blank" href="https://www.npmjs.com/package/koishi-plugin-milk-ikun">
        <img src="https://img.shields.io/npm/v/koishi-plugin-milk-ikun?color=527dec&label=&">
    </a>
</h3>
`;t.Config=k.Schema.object({ikunKeywords:k.Schema.dict(String).default({"2.5":"2.4999999999",两年半:"哼! 你才练习了两年半呢! 不许黑我家哥哥",你干嘛:"小黑子, 露出鸡脚了吧",只因:"小黑子, 露出鸡脚了吧",114514:"哼哼哼~啊啊啊啊"}).role("table").description("将指定关键字 key 替换为 value **支持正则表达式**"),test:k.Schema.path({allowCreate:!0})});async function M(r,e){if(!await(0,K.countryCheck)(r)){t.usage="# Your country or region is not supported because of cultural difference.",t.Config=k.Schema.object({}),x.logger.error(`unsupported country or region! stop loading ${t.name}!`);return}r.on("before-send",n=>{for(let u in e.ikunKeywords)n.content=n.content.replace(new RegExp(u),e.ikunKeywords[u])})}t.apply=M});export default O();
