var q=Object.defineProperty;var G=Object.getOwnPropertyDescriptor;var Q=Object.getOwnPropertyNames;var R=Object.prototype.hasOwnProperty;var w=(e,t)=>()=>(e&&(t=e(e=0)),t);var B=(e,t)=>()=>(t||e((t={exports:{}}).exports,t),t.exports);var j=(e,t,o,n)=>{if(t&&typeof t=="object"||typeof t=="function")for(let s of Q(t))!R.call(e,s)&&s!==o&&q(e,s,{get:()=>t[s],enumerable:!(n=G(t,s))||n.enumerable});return e},a=(e,t,o)=>(j(e,t,"default"),o&&j(o,t,"default"));var b=e=>j(q({},"__esModule",{value:!0}),e);import{Buffer as h}from"https://registry.koishi.chat/modules/buffer/index.js";import d from"https://registry.koishi.chat/modules/process/index.js";var p=w(()=>{});var f={};import*as _e from"https://registry.koishi.chat/modules/koishi/index.js";var C=w(()=>{p();a(f,_e)});var v={};import*as we from"https://registry.koishi.chat/modules/@koishijs/plugin-console/index.js";var A=w(()=>{p();a(v,we)});import U from"https://registry.koishi.chat/modules/@cordiverse/path/index.js";var F=B((Se,E)=>{p();E.exports=U});var g={};import*as Le from"https://registry.koishi.chat/modules/@cordiverse/fs/promises/index.js";var D=w(()=>{p();a(g,Le)});var _={};import*as Ie from"https://registry.koishi.chat/modules/buffer/index.js";var N=w(()=>{p();a(_,Ie)});var me=B((Pe,W)=>{p();var k=Object.defineProperty,X=Object.getOwnPropertyDescriptor,Y=Object.getOwnPropertyNames,Z=Object.prototype.hasOwnProperty,S=(e,t)=>k(e,"name",{value:t,configurable:!0}),ee=(e,t)=>{for(var o in t)k(e,o,{get:t[o],enumerable:!0})},te=(e,t,o,n)=>{if(t&&typeof t=="object"||typeof t=="function")for(let s of Y(t))!Z.call(e,s)&&s!==o&&k(e,s,{get:()=>t[s],enumerable:!(n=X(t,s))||n.enumerable});return e},re=e=>te(k({},"__esModule",{value:!0}),e),H={};ee(H,{Config:()=>ue,apply:()=>K,name:()=>pe,usage:()=>ce});W.exports=re(H);var i=(C(),b(f)),oe=(A(),b(v)),se=F(),z=(D(),b(g)),ae=(D(),b(g)),ie=(N(),b(_)),ne=class{constructor(e,t){this.date=e,this.path=t,this.task=(0,ae.open)(t,"a+").then(async o=>{let n=await o.readFile();return this.data=this.parse(new TextDecoder().decode(n)),this.size=n.byteLength,o}),this.task.then(()=>this.flush())}static{S(this,"FileWriter")}data;task;size;temp=[];flush(){this.temp.length&&(this.task=this.task.then(async e=>{let t=ie.Buffer.from(this.temp.map(o=>JSON.stringify(o)+`
`).join(""));return this.data.push(...this.temp),this.temp=[],await e.write(t),this.size+=t.byteLength,e}))}parse(e){return e.split(`
`).map(t=>{try{return JSON.parse(t)}catch{}}).filter(Boolean)}async read(){return await this.task,this.data}write(e){this.temp.push(e),this.flush()}async close(){await(await this.task).close()}},pe="logger",ce=`
---

方便地修改logger的设置~

灵感来自 https://forum.koishi.xyz/t/topic/6363

---
`,le=class extends oe.DataService{constructor(e,t){super(e,"logs",{authority:4}),this.getWriter=t,e.console.addEntry(["https://registry.koishi.chat/modules/koishi-plugin-logger-logs/dist/index.js","https://registry.koishi.chat/modules/koishi-plugin-logger-logs/dist/style.css"])}static{S(this,"LogProvider")}async get(){return this.getWriter()?.read()}},ue=i.Schema.object({root:i.Schema.path({filters:["directory"],allowCreate:!0}).default("data/logs").description("存放输出日志的本地目录。"),maxAge:i.Schema.natural().description("日志文件保存的最大天数（天）。").default(30),maxSize:i.Schema.natural().description("单个日志文件的最大大小（字节）。").default(1024*100),levels:i.Schema.dict(i.Schema.natural().default(3)).description("指定模块的输出等级。<br>示例： 左侧写 `debug`，右侧写 `3`")});async function K(e,t){let o={},n=t.levels??{};"debug"in n&&(o.base=i.Logger.levels.base,i.Logger.levels.base=n.debug);for(let r in n)r!=="debug"&&(o[r]=i.Logger.levels[r],i.Logger.levels[r]=n[r]);let s=(0,se.resolve)(e.baseDir,t.root);await(0,z.mkdir)(s,{recursive:!0});let c={};for(let r of await(0,z.readdir)(s)){let u=/^(\d{4}-\d{2}-\d{2})-(\d+)\.log$/.exec(r);u&&(c[u[1]]??=[],c[u[1]].push(+u[2]))}let m;async function x(r,u){m=new ne(r,`${s}/${r}-${u}.log`);let{maxAge:l}=t;if(!l)return;let O=Date.now();for(let L of Object.keys(c))if(!(O-+new Date(L)<l*i.Time.day)){for(let T of c[L])await(0,z.rm)(`${s}/${L}-${T}.log`).catch(V=>{e.logger("logger").warn(V)});delete c[L]}}S(x,"createFile");let $=new Date().toISOString().slice(0,10);x($,Math.max(...c[$]??[0])+1);let I=[],J=0,M=e.throttle(()=>{e.get("console")?.patch("logs",I),I=[]},100),y=e.get("loader"),P={colors:3,record:S(r=>{r.id||(r.id=++J),r.meta||={};let u=r.meta[i.Context.current]?.scope;y&&u&&(r.meta.paths=y.paths(u));let l=new Date(r.timestamp).toISOString().slice(0,10);if(m.date!==l&&(m.close(),c[l]=[1],x(l,1)),m.write(r),I.push(r),M(),m.size>=t.maxSize){m.close();let O=Math.max(...c[l]??[0])+1;c[l]??=[],c[l].push(O),x(l,O)}},"record")};i.Logger.targets.push(P),e.on("dispose",()=>{m?.close(),(0,i.remove)(i.Logger.targets,P),y&&(y.prolog=[]);for(let r in o)i.Logger.levels[r]=o[r]});for(let r of y?.prolog||[])P.record(r);e.plugin(le,()=>m)}S(K,"apply")});export default me();
